services:
  - type: web
    name: MeningSoqqam
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
